name: publish
on: 
  workflow_dispatch:
  push:
    tags: [ v* ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload-url: ${{ steps.create_release.outputs.upload_url}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Set upload-url
      run: echo "::set-output name=upload-url::${{ steps.create_release.outputs.upload_url }}"
  release-docker-image: # build and push docker image (this includes a gradle build running in docker)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/mycarrier-devops/redpanda-rpk
        tags: type=ref,event=tag
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        repository: ${{ env.REPO }}
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}